var euler = {
		problem1: {
			question: "If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23. \n\
						Find the sum of all the multiples of 3 or 5 below 1000.",

			solve: function(num) {
						var multiples = [];
						for (var i = 1; i < num; i++) {
							if (i % 3  === 0 | i % 5 === 0) {
								multiples.push(i);
							}
						}
						return multiples.reduce((a, b) => a + b, 0);
					} 
		},

		problem2: {
			question: "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: \n\
						1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... \n\
						By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.",

			solve: function(num) {
						var fibonacci = [0,1];
						var i;
						while (fibonacci[fibonacci.length - 1] < num) {
							i = fibonacci[fibonacci.length - 2] + fibonacci[fibonacci.length - 1];
							fibonacci.push(i);
							console.info(fibonacci);
						}
						fibonacci.pop();
						return fibonacci.filter((a) => a % 2 === 0).reduce((a, b) => a + b, 0);
					}
		},

		problem3: {
			question: "The prime factors of 13195 are 5, 7, 13 and 29. \n\
						What is the largest prime factor of the number 600851475143?",

			solve: function(num) {
						var primes = [2,3,5,7,11,13];
						var range = num;
						var sR = Math.ceil(Math.sqrt(range));
						console.log("Calculating Prime Numbers....");
						var start = Date.now()
						for (i=15;i<sR;i+=2) {
							var isPrime = true;
							var b = Math.ceil(Math.sqrt(i));
							for (j=0; primes[j] <= b; j++) {
								if (i % primes[j] === 0) { 
									isPrime = false; 
									break; 
								} 
							}		
							if (isPrime) { primes.push(i); }	
						}
						console.log("Finished Calculating Prime Numbers");

						for (k=primes.length-1; k >= 0; k-- ) {
							if (num % primes[k] === 0) {
								return primes[k];
							}
						}
					}
		},

		problem4: {
			question: "A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99. \n\
						Find the largest palindrome made from the product of two 3-digit numbers.",
		},

		problem5: {
			question: "2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder. \n\
						What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?",

			solve: function(num) {
						var divisible = false;
						var number = 1;
						var i = 1;
						do {
							for (i = 1; i < num+1; i++) {
									if (number % i !== 0) {
										divisible = false;
										number = number + 1;
										break;	
									}
								//console.log(i);
								if (i === num) {
									divisible = true;
									break;
								}
							}
						} while (divisible === false);
						return number;
					}
		},

		problem6: {
			question: "The sum of the squares of the first ten natural numbers is, \n\
						1^2 + 2^2 + ... + 10^2 = 385 \n\
\						The square of the sum of the first ten natural numbers is,\n\
						(1 + 2 + ... + 10)^2 = 55^2 = 3025 \n\
\						Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640. \n\
\						Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.",
		
			solve: function(num) {
						var numbers = [];
						for (var i = 1; i <= num; i++) {
							numbers.push(i);
						};

						var squareNums = numbers.map(function(x) {
							return x * x;
						});

						var sumOfNums = numbers.reduce((a,b) => a + b, 0);
						var sumOfSqaures = squareNums.reduce((a,b) => a + b, 0);
						var squareOfSum = (sumOfNums)*(sumOfNums);
						var difference = squareOfSum - sumOfSqaures;

						return difference;
					}
		},

		problem7: {
			question: "By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13. \n\
\						What is the 10,001st prime number?",

		},

		problem8: {
			question: "The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832. \n\
\n\
						73167176531330624919225119674426574742355349194934\n\
						96983520312774506326239578318016984801869478851843\n\
						85861560789112949495459501737958331952853208805511\n\
						12540698747158523863050715693290963295227443043557\n\
						66896648950445244523161731856403098711121722383113\n\
						62229893423380308135336276614282806444486645238749\n\
						30358907296290491560440772390713810515859307960866\n\
						70172427121883998797908792274921901699720888093776\n\
						65727333001053367881220235421809751254540594752243\n\
						52584907711670556013604839586446706324415722155397\n\
						53697817977846174064955149290862569321978468622482\n\
						83972241375657056057490261407972968652414535100474\n\
						82166370484403199890008895243450658541227588666881\n\
						16427171479924442928230863465674813919123162824586\n\
						17866458359124566529476545682848912883142607690042\n\
						24219022671055626321111109370544217506941658960408\n\
						07198403850962455444362981230987879927244284909188\n\
						84580156166097919133875499200524063689912560717606\n\
						05886116467109405077541002256983155200055935729725\n\
						71636269561882670428252483600823257530420752963450\n\
\n\
						Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?",

		},

		problem9: {
			question: "A Pythagorean triplet is a set of three natural numbers, a < b < c, for which, \n\
\n\
						a^2 + b^2 = c^2 \n\
\n\
						For example, 3^2 + 4^2 = 9 + 16 = 25 = 52. \n\
\n\
						There exists exactly one Pythagorean triplet for which a + b + c = 1000. \n\
						Find the product abc.",

			solve: "The answer is a = 200, b = 375, c = 425. \n\
					abc = 31,875,000 \n\
					If 1000 is divisble exactly by the sum of the primitive primes, then the answer is the product of the primitive primes with the result of that division "

		},

		problem50: {
			question: "The prime 41, can be written as the sum of six consecutive primes: \n\
						41 = 2 + 3 + 5 + 7 + 11 + 13 \n\
						This is the longest sum of consecutive primes that adds to a prime below one-hundred. \n\
						The longest sum of consecutive primes below one-thousand that adds to a prime, contains 21 terms, and is equal to 953. \n\
						Which prime, below one-million, can be written as the sum of the most consecutive primes?",

			solve : function (num) {
						var primes = [2,3,5,7,11,13];
						var range = num;
						
						console.log("Calculating Prime Numbers....");
						var start = Date.now()
						for (i=15;i<num;i+=2) {
							var isPrime = true;
							var b = Math.ceil(Math.sqrt(i));
							for (j=0; primes[j] <= b; j++) {
								if (i % primes[j] === 0) { 
									isPrime = false; 
									break; 
								} 
							}		
							if (isPrime) { primes.push(i); }	
						}
						console.log("Finished Calculating Prime Numbers");
										
						var answerLength = 0;
						var answerNumber = 0;
						for (j=primes.length-1; j>=0; j--) {
							
							var halfJ = primes[j]/2;
							var index = 0;
							for (m=0; m < j; m++) {
								if (primes[m] > halfJ) {
									index = m;
									break;
								}
							}
							if (answerLength < j) {
								for (k=0; index-k > answerLength; k++) {
									var count = 0;
									var sum = 0;
									for (i=k; i < j; i++) {
										sum = sum + primes[i];
										count++;
										if (sum === primes[j]) {
											if (count > answerLength) {
												answerLength = count;
												answerNumber = sum;
												break;
											}
										} 
										else if (sum > primes[j]) {
											break;
										}
									}
								}
							}
						}
						return answerNumber;
					}
		}
}